### ISSUE TITLE
Is C# scripting no longer supported?

### ISSUE THREAD

**Issue by akaymd** [thiagomiranda3/PlaystationMacro#2]
I was using C# scripting on API described in README.md with komefai's PS4Macro.
But, it no longer works.
It seems DualShockState in ScriptBase has been changed to byte[] .

komefai's
`public ScriptBase Press(DualShockState state, int delay = DEFAULT_PRESS_BUTTONS_DELAY)`

yours
`public ScriptBase Press(byte[] state, int delay = DEFAULT_PRESS_BUTTONS_DELAY)`

How can I create state of byte[] ?

**Comment by thiagomiranda3** [comment]
Yes. No longer supported, I still need to remove them completely to be more explicit about it.
But the reason for changing to byte[] is that PS4 and PS5 have different protocols for sending data, so I need to store the data they send directly as it comes, otherwise, we lose the compatibility with either PS4 or PS5.

**Comment by akaymd** [comment]
Understood.
Looking forward to adding a programmable interface in the future, if possible.

Thank you for your response.

**Comment by BobbyB883** [comment]
I know this is closed/dead but there is a bandaid workaround to get scripting to work, just record each button press as its own macro and in the script play that macro file when you need a certain button press

```
        public override void Update()
        {
            Console.WriteLine("Simulating DPad Right press via macro file.");

            Host.PlayMacro("Dpad_Right.xml", suspendDelay: 1000);

            Sleep(2000);

            Console.WriteLine("Simulating DPad Down press via macro file.");

            Host.PlayMacro("Dpad_Down.xml", suspendDelay: 1000);

            Sleep(2000);

            Console.WriteLine("Simulating DPad Left press via macro file.");

            Host.PlayMacro("Dpad_Left.xml", suspendDelay: 1000);

            Sleep(2000);

            Console.WriteLine("Simulating DPad Up press via macro file.");

            Host.PlayMacro("Dpad_Up.xml", suspendDelay: 1000);
            Sleep(2000);
        }
```
